import pytest

from saidkick.mcp_server import build_mcp

VS1_TOOLS = {
    "list_contexts",
    "open_context",
    "close_context",
    "list_tabs",
    "open_tab",
    "close_tab",
    "navigate",
    "snapshot_page",
    "find",
    "click",
    "type",
    "press",
    "select",
    "highlight",
    "screenshot",
    "get_events",
}
VS2_TOOLS = {"request_human", "control_state"}


async def _descriptions(engine, controller):
    tools = await build_mcp(engine, controller).list_tools()
    return {t.name: t.description or "" for t in tools}


async def test_all_tools_registered(engine, controller):
    names = set(await _descriptions(engine, controller))
    assert VS1_TOOLS <= names
    assert VS2_TOOLS <= names


async def test_every_tool_has_a_real_description(engine, controller):
    """Descriptions are a deliverable, not autogenerated stubs."""
    for name, desc in (await _descriptions(engine, controller)).items():
        assert len(desc) > 60, f"{name} has a stub description"


async def test_snapshot_description_states_aria_preference(engine, controller):
    d = (await _descriptions(engine, controller))["snapshot_page"]
    assert "aria" in d.lower()
    assert "last resort" in d.lower()


async def test_open_context_description_explains_ephemeral(engine, controller):
    d = (await _descriptions(engine, controller))["open_context"].lower()
    assert "ephemeral" in d and "isolated" in d


async def test_request_human_obliges_the_agent_to_relay(engine, controller):
    """The agent's own words are the most reliable notification channel."""
    d = (await _descriptions(engine, controller))["request_human"]
    lower = d.lower()
    assert "relay" in lower or "tell your operator" in lower
    assert "still_waiting" in d
    assert "human_message" in d
    assert "silently" in lower


async def test_request_human_documents_both_durations(engine, controller):
    """deadline_s and poll_s are independent; conflating them is the obvious trap."""
    d = (await _descriptions(engine, controller))["request_human"]
    assert "deadline_s" in d and "poll_s" in d and "independent" in d.lower()


async def test_locator_guidance_reaches_the_acting_tools(engine, controller):
    d = await _descriptions(engine, controller)
    for name in ("click", "type", "press", "select", "find"):
        assert "by_role" in d[name], f"{name} does not document locators"


async def test_highlight_is_described_as_pointing_for_the_human(engine, controller):
    d = (await _descriptions(engine, controller))["highlight"].lower()
    assert "human" in d


@pytest.mark.browser
async def test_tools_actually_drive_the_browser(engine, controller, fixture_url):
    """Descriptions aside, the wiring has to work."""
    mcp = build_mcp(engine, controller)
    ctx = await engine.open_context()
    tab = await ctx.open_tab(f"{fixture_url}/form.html")

    snap = await mcp.call_tool("snapshot_page", {"tab": tab.id})
    assert 'button "Send"' in str(snap)

    await mcp.call_tool("type", {"tab": tab.id, "text": "erin", "css": "#u"})
    await mcp.call_tool("click", {"tab": tab.id, "css": "#go"})
    text = await mcp.call_tool("snapshot_page", {"tab": tab.id, "mode": "text"})
    assert "submitted:erin" in str(text)


@pytest.mark.browser
async def test_request_human_tool_returns_a_relayable_message(engine, controller):
    mcp = build_mcp(engine, controller)
    ctx = await engine.open_context()
    out = await mcp.call_tool(
        "request_human",
        {"context": ctx.id, "reason": "solve the captcha", "deadline_s": 0.2, "poll_s": 0.1},
    )
    assert "solve the captcha" in str(out)
