import pytest

from saidkick.mcp_server import build_mcp

VS1_TOOLS = {
    "list_contexts",
    "open_context",
    "close_context",
    "list_tabs",
    "open_tab",
    "close_tab",
    "navigate",
    "snapshot_page",
    "find",
    "click",
    "type",
    "press",
    "select",
    "highlight",
    "screenshot",
    "get_events",
}
VS2_TOOLS = {"request_human", "control_state"}
VS4_TOOLS = {"list_pins", "read_pin"}
VS3_TOOLS = {"list_profiles", "save_profile"}


async def _descriptions(engine, controller):
    tools = await build_mcp(engine, controller).list_tools()
    return {t.name: t.description or "" for t in tools}


async def test_all_tools_registered(engine, controller):
    names = set(await _descriptions(engine, controller))
    assert names >= VS1_TOOLS
    assert names >= VS2_TOOLS
    assert names >= VS4_TOOLS
    assert names >= VS3_TOOLS


async def test_open_context_documents_modes_and_bootstrapping(engine, controller):
    d = (await _descriptions(engine, controller))["open_context"].lower()
    assert "attached" in d and "ephemeral" in d
    assert "indexeddb" in d  # the ephemeral-seeding caveat
    assert "save_profile" in d  # the bootstrapping pointer


async def test_save_profile_describes_the_human_solved_login_flow(engine, controller):
    d = (await _descriptions(engine, controller))["save_profile"].lower()
    assert "request_human" in d or "human" in d
    assert "signed in" in d or "login" in d


async def test_read_pin_tells_the_agent_to_fall_back_on_stale(engine, controller):
    d = (await _descriptions(engine, controller))["read_pin"]
    assert "StaleHandle" in d
    assert "suggested_locator" in d or "xpath" in d


async def test_list_pins_says_humans_place_them(engine, controller):
    d = (await _descriptions(engine, controller))["list_pins"].lower()
    assert "human" in d and "cannot create" in d


async def test_acting_tools_document_the_handle_option(engine, controller):
    d = await _descriptions(engine, controller)
    for name in ("click", "type", "find"):
        assert "handle" in d[name].lower(), name


@pytest.mark.browser
async def test_click_via_handle_submits_the_form(engine, controller, fixture_url):
    from saidkick.pins import PinRegistry

    pins = PinRegistry()
    mcp = build_mcp(engine, controller, pins=pins)
    ctx = await engine.open_context()
    tab = await ctx.open_tab(f"{fixture_url}/form.html")
    box = await tab.page.locator("#go").bounding_box()
    pin = await pins.mint_point(tab, box["x"] + box["width"] / 2, box["y"] + box["height"] / 2)

    await mcp.call_tool("type", {"tab": tab.id, "text": "viahandle", "css": "#u"})
    await mcp.call_tool("click", {"tab": tab.id, "handle": pin.id})
    text = await mcp.call_tool("snapshot_page", {"tab": tab.id, "mode": "text"})
    assert "submitted:viahandle" in str(text)


@pytest.mark.browser
async def test_read_pin_returns_the_bundle(engine, controller, fixture_url):
    from saidkick.pins import PinRegistry

    pins = PinRegistry()
    mcp = build_mcp(engine, controller, pins=pins)
    ctx = await engine.open_context()
    tab = await ctx.open_tab(f"{fixture_url}/form.html")
    box = await tab.page.locator("#go").bounding_box()
    pin = await pins.mint_point(tab, box["x"] + box["width"] / 2, box["y"] + box["height"] / 2)

    out = await mcp.call_tool("read_pin", {"handle": pin.id})
    assert "BUTTON" in str(out)


async def test_every_tool_has_a_real_description(engine, controller):
    """Descriptions are a deliverable, not autogenerated stubs."""
    for name, desc in (await _descriptions(engine, controller)).items():
        assert len(desc) > 60, f"{name} has a stub description"


async def test_snapshot_description_states_aria_preference(engine, controller):
    d = (await _descriptions(engine, controller))["snapshot_page"]
    assert "aria" in d.lower()
    assert "last resort" in d.lower()


async def test_open_context_description_explains_ephemeral(engine, controller):
    d = (await _descriptions(engine, controller))["open_context"].lower()
    assert "ephemeral" in d and "isolated" in d


async def test_request_human_obliges_the_agent_to_relay(engine, controller):
    """The agent's own words are the most reliable notification channel."""
    d = (await _descriptions(engine, controller))["request_human"]
    lower = d.lower()
    assert "relay" in lower or "tell your operator" in lower
    assert "still_waiting" in d
    assert "human_message" in d
    assert "silently" in lower


async def test_request_human_documents_both_durations(engine, controller):
    """deadline_s and poll_s are independent; conflating them is the obvious trap."""
    d = (await _descriptions(engine, controller))["request_human"]
    assert "deadline_s" in d and "poll_s" in d and "independent" in d.lower()


async def test_locator_guidance_reaches_the_acting_tools(engine, controller):
    d = await _descriptions(engine, controller)
    for name in ("click", "type", "press", "select", "find"):
        assert "by_role" in d[name], f"{name} does not document locators"


async def test_highlight_is_described_as_pointing_for_the_human(engine, controller):
    d = (await _descriptions(engine, controller))["highlight"].lower()
    assert "human" in d


@pytest.mark.browser
async def test_tools_actually_drive_the_browser(engine, controller, fixture_url):
    """Descriptions aside, the wiring has to work."""
    mcp = build_mcp(engine, controller)
    ctx = await engine.open_context()
    tab = await ctx.open_tab(f"{fixture_url}/form.html")

    snap = await mcp.call_tool("snapshot_page", {"tab": tab.id})
    assert 'button "Send"' in str(snap)

    await mcp.call_tool("type", {"tab": tab.id, "text": "erin", "css": "#u"})
    await mcp.call_tool("click", {"tab": tab.id, "css": "#go"})
    text = await mcp.call_tool("snapshot_page", {"tab": tab.id, "mode": "text"})
    assert "submitted:erin" in str(text)


@pytest.mark.browser
async def test_request_human_tool_returns_a_relayable_message(engine, controller):
    mcp = build_mcp(engine, controller)
    ctx = await engine.open_context()
    out = await mcp.call_tool(
        "request_human",
        {"context": ctx.id, "reason": "solve the captcha", "deadline_s": 0.2, "poll_s": 0.1},
    )
    assert "solve the captcha" in str(out)
